version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  pre_build:
    commands:
      - echo creating build directories and fetching dependencies...
      - mkdir lib
      - mkdir -p src/rce/main/domain/rce-domain/1.0/
      - echo copying dependencies from s3 to build path
      # - aws s3 cp s3://codepipeline-eu-west-1-nswws-code-repo/release/rce-domain-1.0.jar src/main/resources/rce-domain-1.0.jar
      - aws s3 cp s3://codepipeline-eu-west-1-nswws-code-repo/release/rce-domain-1.0.jar src/main/rce/domain/rce-domain/1.0/rce-domain-1.0.jar
#      - cd src
#      - ls -l
#      - cd rce
#      - ls -l
#      - cd domain
#      - ls -l
#      - cd rce-domain
#      - ls -l
#      - cd 1.0
#      - ls -l
      - echo pre-build phase completed on `date`
#  build:
#    commands:
#      - echo build phase started on `date`
#      - echo running maven test phase
#      - mvn test
#      - echo build phase completed on `date`
  post_build:
    commands:
      - echo post-build phase started on `date`
      - mvn package
      - echo copying build artifact rce-lambda-develop.jar to S3 target directory
      - aws s3 cp target/rce-lambda-develop.jar s3://codepipeline-eu-west-1-nswws-lambda-target/build/rce-lambda-develop.jar
      - echo post-build completed on `date`
