version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  build:
    commands:
      - echo Build test stage started on `date`
      - mvn package
  post_build:
    commands:
#      - cd target
      - echo file list
      - ll
#      - cp target/rce-lambda-develop.jar lib/rce-lambda-develop.jar
artifacts:
  files:
    - target/rce-lambda-develop.jar