version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  pre_build:
    commands:
      - echo creating build directories and fetching dependencies...
      - mkdir lib
      - echo copying dependencies from s3 to build path
      - aws s3 cp s3://codepipeline-eu-west-1-nswws-code-repo/release/rce-domain-1.0.jar src/main/resources
      - echo listing resources
      - cd src/main/resources
      - ls -l
  build:
    commands:
      - echo build phase started on `date`
      - echo running maven test phase
      - mvn test
  post_build:
    commands:
      - mvn package
      - echo copying build artifact to S3 target directory
      - aws s3 cp target/rce-lambda-develop.jar s3://codepipeline-eu-west-1-nswws-lambda-target/build/rce-lambda-develop.jar
      - echo post build completed on `date`
#artifacts:
#  files:
#    - lib/rce-lambda-develop.jar
#  discard-paths: yes
#  packaging: zip
#  namespaceType : none
#  type: s3
#  location: S3://codepipeline-eu-west-1-nswws-lambda-target
#  path: rich-pipeline/build
#  name: rce-lambda-develop.jar