version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  pre_build:
    commands:
      - echo creating build directories and fetching dependencies...
      - mkdir lib
      - echo copying dependencies from s3 to build path
      - aws s3 cp s3://codepipeline-eu-west-1-nswws-code-repo/release/rce-domain-1.0.jar src/main/resources/rce-domain-1.0.jar
      # install domain artifact to local build
      - mvn install:install-file -Dfile=src/main/resources/rce-domain-1.0.jar -DgroupId=rce.domain -DartifactId=rce-domain -Dversion=1.0 -Dpackaging=jar
      - echo pre-build phase completed on `date`
  build:
    commands:
      - echo build phase started on `date`
      - echo running maven test phase
      # - mvn test
  post_build:
    commands:
      - echo post-build phase started on `date`
      - mvn package
      - echo copying build artifact rce-lambda-develop.jar to S3 target directory
      - aws s3 cp target/rce-lambda-develop.jar s3://codepipeline-eu-west-1-nswws-lambda-target/build/rce-lambda-develop.jar

      # - aws lambda create-function --function-name rce-test-lambda-cli --runtime java8 --role arn:aws:iam::894951693940:role/nswws_alpha_lambda_execute_role --handler uk.gov.metoffice.nswws.dissemination.handler.RichiesEventHandler::handleRequest --code S3Bucket=codepipeline-eu-west-1-nswws-lambda-target,S3Key=/build/rce-lambda-develop.jar,S3ObjectVersion=1.0 --timeout 30 --memory-size 128
      - ls -l
      - echo post-build completed on `date`
artifacts:
  type: zip
  files:
    # build file is included in the github repo
    - rce_simple_lambda_cloud_formation_template.yml