version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mkdir lib
  build:
    commands:
      - echo build phase started on `date`
      - mvn test
  post_build:
    commands:
      - echo post build completed on `date`
      - mvn package
      - cp target/rce-lambda-develop.jar lib/rce-lambda-develop.jar
      - cd lib
      - ls -l
      - echo finished build
artifacts:
  files:
    - lib/rce-lambda-develop.jar