version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  build:
    commands:
      - echo Build test stage started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build package phase completed on `date`
      - mvn package
artifacts:
  files:
    - test/rce-lambda-develop.jar
